[app]
tr-app ansible_host=192.168.0.160 owner=Vasya

[dev]
#radius  ansible_host=10.16.3.105
log-stat ansible_host=172.16.16.25
tr-app ansible_host=192.168.0.160
#qa-dev ansible_host=172.20.12.21 owner=Kolya
