---
- name: Install PHP-FPM and Configure Website
  hosts: app
  become: yes
  vars_files:
    - env.yml
  tasks:
    - name: Determine OS Version
      include_vars:
        dir: "{{ ansible_facts.distribution_release }}"
        fail_on_unkown: no
      when: ansible_distribution in ['Rocky', 'OracleLinux'] and ansible_distribution_version in ['8', '9']

    - name: Install PHP-FPM
      package:
        name: "php{{ php_version }}-fpm"
        state: present
      vars:
        php_version: "{{ php_version }}"
      when: os_version is defined

    - name: Create PHP-FPM Configuration
      template:
        src: site.conf.j2
        dest: /etc/php-fpm.d/{{ site_name }}.conf
      vars:
        site_name: "{{ site_name }}"
      notify: Restart PHP-FPM

    - name: Start PHP-FPM Service
      service:
        name: php{{ php_version }}-fpm
        state: started
        enabled: yes
      vars:
        php_version: "{{ php_version }}"
      when: os_version is defined

  handlers:
    - name: Restart PHP-FPM
      service:
        name: php{{ php_version }}-fpm
        state: restarted
      vars:
        php_version: "{{ php_version }}"

