---
- name: Print OS version
  debug:
    msg: “The OS version is {{ ansible_distribution }} and {{ os_version }}"
- name: Install PHP-FPM
  package:
     name: "php{{ php_version }}-php-fpm"
     state: present
  when: os_distribution in ['Rocky', 'CentOS'] and os_version in ['7', '9']
- name: Create PHP-FPM Configuration
  template:
    src: site.conf.j2
    dest: /etc/php-fpm.d/{{ site_name }}.conf
  notify: Restart PHP-FPM
  when: os_distribution in ['Rocky', 'CentOS'] and os_version in ['7', '9']
- name: Start PHP-FPM Service
  service:
    name: php-fpm
    state: started
    enabled: yes
  when: os_distribution in ['Rocky', 'OracleLinux'] and os_version in ['7', '9']